site_name: Accounting Matura Documentation
site_description: Documentation for the Accounting Matura
site_author: Fabian Rossmann
edit_uri: ""

theme:
    name: readthedocs

nav:
    - Home: index.md
    - User Guide:
      - 'Pool 1': 'pool1.md'
      - 'Pool 2': 'pool2.md'
      - 'Pool 3': 'pool3.md'
    
copyright: Copyright &copy; 2018 Fabian Rossmann